Repository cloudforet-io/repository, pull requests merged in 2023-10, with the labels that each got.

#22 Modify long_description at plugin-azure-inven-collector.yaml
  src/spaceone/repository/managed_resource/plugin/plugin-azure-inven-collector.yaml
Labels: documentation

#23 Modify yaml of Google Service in repo-managed type
  src/spaceone/repository/managed_resource/plugin/plugin-google-cloud-inven-collector.yaml
  src/spaceone/repository/managed_resource/plugin/plugin-google-cloud-log-mon-datasource.yaml
  src/spaceone/repository/managed_resource/plugin/plugin-google-monitoring-mon-webhook.yaml
Labels: documentation

#24 chore: added new labels and changed description at plugin-aws-cloud-s…
  src/spaceone/repository/managed_resource/plugin/plugin-aws-cloud-service-inven-collector.yaml
Labels: documentation

#25 Add schema of telegram auth token in repo-managed
  src/spaceone/repository/managed_resource/schema/telegram_auth_token.yaml
Labels: documentation

#26 Change MAX_IMAGE_NAME_LENGTH variable
  src/spaceone/repository/service/plugin_service.py
Labels: enhancement

#27 Change MAX_IMAGE_NAME_LENGTH variable 80 to 48
  src/spaceone/repository/service/plugin_service.py
Labels: bug

#28 Add registry_type of AWSPrivateECR in plugin_info
  src/spaceone/repository/conf/global_conf.py
  src/spaceone/repository/info/plugin_info.py
Labels: bug

#29 Add AWS_PRIVATE_ECR value in REGISTRY_URL_MAP
  src/spaceone/repository/conf/global_conf.py
Labels: enhancement

#30 Refactor registry_config field in plugin_info
  src/spaceone/repository/conf/global_conf.py
  src/spaceone/repository/connector/registry_connector.py
  src/spaceone/repository/info/plugin_info.py
  src/spaceone/repository/manager/plugin_manager/local_plugin_manager.py
  src/spaceone/repository/manager/plugin_manager/managed_plugin_manager.py
  src/spaceone/repository/service/plugin_service.py
Labels: enhancement

#32 Fix imagePullSecrets variables
  src/spaceone/repository/conf/global_conf.py
Labels: bug
