Repository cloudforet-io/repository, pull requests merged in 2024-04, with the labels that each got.

#60 Add yaml file of Recommender Collector
  src/spaceone/repository/managed_resource/plugin/plugin-google-recommender-inven-collector.yaml
Labels: enhancement

#61 Modify image in yaml file of recommender collector
  src/spaceone/repository/managed_resource/plugin/plugin-google-recommender-inven-collector.yaml
Labels: bug

#62 Add managed identity account collectors plugin
  src/spaceone/repository/managed_resource/plugin/plugin-aws-identity-account-collector.yaml
  src/spaceone/repository/managed_resource/plugin/plugin-azure-identity-account-collector.yaml
  src/spaceone/repository/managed_resource/plugin/plugin-google-cloud-identity-account-collector.yaml
Labels: enhancement, fail/signedoff

#63 Add managed schema
  src/spaceone/repository/managed_resource/plugin/plugin-k8s-opencost-cost-datasource.yaml
Labels: enhancement, pass/signedoff

#64 Temporary remove k8s managed resource
  src/spaceone/repository/managed_resource/plugin/plugin-k8s-opencost-cost-datasource.yaml
Labels: enhancement, pass/signedoff

#65 Add k8s managed resource
  src/spaceone/repository/managed_resource/plugin/plugin-k8s-opencost-cost-datasource.yaml
Labels: enhancement, pass/signedoff

#66 feat: change image name for aws plugin compatability
  src/spaceone/repository/managed_resource/plugin/plugin-aws-ec2-inven-collector.yaml
Labels: fail/signedoff
